using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace MidiKeyboard
{
    public class Instrument
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string TranslatedName { get; set; }

        public static List<Instrument> GetAllInstruments()
        {
            return new List<Instrument> 
            {
new Instrument { Id = 0, Name = "Acoustic Piano", TranslatedName = "Фортепиано"},
new Instrument { Id = 1, Name = "Bright Piano", TranslatedName = "Концертный рояль"},
new Instrument { Id = 2, Name = "Electric Grand Piano", TranslatedName = "Электрический рояль"},
new Instrument { Id = 3, Name = "Honky Tonk Piano", TranslatedName = "Расстроенное фортепиано"},
new Instrument { Id = 4, Name = "Electric Piano I", TranslatedName = "Электропиано 1"},
new Instrument { Id = 5, Name = "Electric Piano II", TranslatedName = "Электропиано 2"},
new Instrument { Id = 6, Name = "Harpsichord", TranslatedName = "Клавесин"},
new Instrument { Id = 7, Name = "Clavinet", TranslatedName = "Клавинет"},
new Instrument { Id = 8, Name = "Celesta", TranslatedName = "Челеста"},
new Instrument { Id = 9, Name = "Glockenspiel", TranslatedName = "Колокольчики"},
new Instrument { Id = 10, Name = "Music Box", TranslatedName = "Музыкальная шкатулка"},
new Instrument { Id = 11, Name = "Vibraphone", TranslatedName = "Вибрафон"},
new Instrument { Id = 12, Name = "Marimba", TranslatedName = "Маримба"},
new Instrument { Id = 13, Name = "Xylophone", TranslatedName = "Ксилофон"},
new Instrument { Id = 14, Name = "Tubular Bells", TranslatedName = "Колокола (трубчатые)"},
new Instrument { Id = 15, Name = "Dulcimer", TranslatedName = "Цимбалы"},
new Instrument { Id = 16, Name = "Drawbar Organ", TranslatedName = "Орган"},
new Instrument { Id = 17, Name = "Percussive Organ", TranslatedName = "Орган с ударной атакой"},
new Instrument { Id = 18, Name = "Rock Organ", TranslatedName = "Рок-орган"},
new Instrument { Id = 19, Name = "Church Organ", TranslatedName = "Церковный орган"},
new Instrument { Id = 20, Name = "Reed Organ", TranslatedName = "Язычковый орган"},
new Instrument { Id = 21, Name = "Accordion", TranslatedName = "Аккордеон"},
new Instrument { Id = 22, Name = "Harmonica", TranslatedName = "Губная гармошка"},
new Instrument { Id = 23, Name = "Tango Accordion", TranslatedName = "Танго-аккордеон"},
new Instrument { Id = 24, Name = "Nylon Guitar", TranslatedName = "Гитара (нейлоновые струны)"},
new Instrument { Id = 25, Name = "Steel String", TranslatedName = "Гитара (стальные струны)"},
new Instrument { Id = 26, Name = "Jazz Guitar", TranslatedName = "Джазовая гитара"},
new Instrument { Id = 27, Name = "Clean Guitar", TranslatedName = "Акустическая соло-гитара"},
new Instrument { Id = 28, Name = "Muted Guitar", TranslatedName = "Приглушенная гитара"},
new Instrument { Id = 29, Name = "Overdriven Guitar", TranslatedName = "Гитара с перемодуляцией"},
new Instrument { Id = 30, Name = "Distortion Guitar", TranslatedName = "Гитара с искажениями (эффект дисторшн)"},
new Instrument { Id = 31, Name = "Guitar Harmonics", TranslatedName = "Гитарные гармоник"},
new Instrument { Id = 32, Name = "Acoustic Bass", TranslatedName = "Бас-гитара"},
new Instrument { Id = 33, Name = "Fingered Bass (Electric Bass)", TranslatedName = "Бас-гитара (пальцевым щипком)"},
new Instrument { Id = 34, Name = "Picked Bass", TranslatedName = "Бас-гитара (медиатором)"},
new Instrument { Id = 35, Name = "Fretless Bass", TranslatedName = "Безладовая бас-гитара"},
new Instrument { Id = 36, Name = "Slap Bass I", TranslatedName = "Слэп 1"},
new Instrument { Id = 37, Name = "Slap Bass II", TranslatedName = "Слэп 2"},
new Instrument { Id = 38, Name = "Synth Bass I", TranslatedName = "Синтезаторный бас 1"},
new Instrument { Id = 39, Name = "Synth Bass II", TranslatedName = "Синтезаторный бас 2"},
new Instrument { Id = 40, Name = "Violin", TranslatedName = "Скрипка"},
new Instrument { Id = 41, Name = "Viola", TranslatedName = "Альт"},
new Instrument { Id = 42, Name = "Cello", TranslatedName = "Виолончель"},
new Instrument { Id = 43, Name = "Contrabass", TranslatedName = "Контрабас"},
new Instrument { Id = 44, Name = "Tremolo Strings", TranslatedName = "Тремолирующие струнные"},
new Instrument { Id = 45, Name = "Pizzicato Strings", TranslatedName = "Струнные пиццикато"},
new Instrument { Id = 46, Name = "Harp", TranslatedName = "Арфа"},
new Instrument { Id = 47, Name = "Timpani", TranslatedName = "Литавры"},
new Instrument { Id = 48, Name = "String Ensemble I", TranslatedName = "Струнные 1"},
new Instrument { Id = 49, Name = "String Ensemble II", TranslatedName = "Струнные 2"},
new Instrument { Id = 50, Name = "Synth Strings I", TranslatedName = "Синтезированные струнные 1"},
new Instrument { Id = 51, Name = "Synth Strings II", TranslatedName = "Синтезированные струнные 2"},
new Instrument { Id = 52, Name = "Choir Aahs", TranslatedName = "Хоровое а"},
new Instrument { Id = 53, Name = "Voice Oohs", TranslatedName = "Голосовое о"},
new Instrument { Id = 54, Name = "Synth Voice", TranslatedName = "Синтезированный голос"},
new Instrument { Id = 55, Name = "Orchestra Hit", TranslatedName = "Оркестровый акцент"},
new Instrument { Id = 56, Name = "Trumpet", TranslatedName = "Труба"},
new Instrument { Id = 57, Name = "Trombone", TranslatedName = "Тромбон"},
new Instrument { Id = 58, Name = "Tuba", TranslatedName = "Туба"},
new Instrument { Id = 59, Name = "Muted Trumpet", TranslatedName = "Засурдиненная труба"},
new Instrument { Id = 60, Name = "French Horn", TranslatedName = "Валторна"},
new Instrument { Id = 61, Name = "Brass Section", TranslatedName = "Медная духовая группа"},
new Instrument { Id = 62, Name = "Synth Brass I", TranslatedName = "Синтезированные медные 1"},
new Instrument { Id = 63, Name = "Synth Brass II", TranslatedName = "Синтезированные медные 2"},
new Instrument { Id = 64, Name = "Soprano Saxophone", TranslatedName = "Сопрановый саксофон"},
new Instrument { Id = 65, Name = "Alto Saxophone", TranslatedName = "Альтовый саксофон"},
new Instrument { Id = 66, Name = "Tenor Saxophone", TranslatedName = "Теноровый саксофон"},
new Instrument { Id = 67, Name = "Baritone Saxophone", TranslatedName = "Баритоновый саксофон"},
new Instrument { Id = 68, Name = "Oboe", TranslatedName = "Гобой"},
new Instrument { Id = 69, Name = "English Horn", TranslatedName = "Английский рожок"},
new Instrument { Id = 70, Name = "Bassoon", TranslatedName = "Фагот"},
new Instrument { Id = 71, Name = "Clarinet", TranslatedName = "Кларнет"},
new Instrument { Id = 72, Name = "Piccolo", TranslatedName = "Флейта пикколо"},
new Instrument { Id = 73, Name = "Flute", TranslatedName = "Флейта"},
new Instrument { Id = 74, Name = "Recorder", TranslatedName = "Блокфлейта"},
new Instrument { Id = 75, Name = "Pan Flute", TranslatedName = "Флейта Пана"},
new Instrument { Id = 76, Name = "Blown Bottle", TranslatedName = "Дуновение в бутылку"},
new Instrument { Id = 77, Name = "Shakuhachi", TranslatedName = "Шакухачи"},
new Instrument { Id = 78, Name = "Whistle", TranslatedName = "Свист"},
new Instrument { Id = 79, Name = "Ocarina", TranslatedName = "Окарина"},
new Instrument { Id = 80, Name = "Square Lead", TranslatedName = "Соло-гитара (прямоугольнаяволна)"},
new Instrument { Id = 81, Name = "Sawtooth Lead", TranslatedName = "Соло-гитара (пилообразная волна)"},
new Instrument { Id = 82, Name = "Calliope Lead", TranslatedName = "Calliope-гитара"},
new Instrument { Id = 83, Name = "Chiff Lead", TranslatedName = "Chiff-гитара"},
new Instrument { Id = 84, Name = "Charang Lead", TranslatedName = "Charang-гитара"},
new Instrument { Id = 85, Name = "Voice Lead", TranslatedName = "Соло-гитара (голосовой тембр)"},
new Instrument { Id = 86, Name = "Fifth Lead", TranslatedName = "Соло-гитара (с квинтовым обертоном)"},
new Instrument { Id = 87, Name = "Bass&Lead", TranslatedName = "Бас и соло-гитара"},
new Instrument { Id = 88, Name = "New Age Pad", TranslatedName = "Синтезаторный звук нью-эйдж"},
new Instrument { Id = 89, Name = "Warm Pad", TranslatedName = "Теплый синтезаторный звук"},
new Instrument { Id = 90, Name = "Polysynth Pad", TranslatedName = "Полисинтезатор"},
new Instrument { Id = 91, Name = "Choir Pad", TranslatedName = "Хоровой синтезаторный звук"},
new Instrument { Id = 92, Name = "Bowed Pad", TranslatedName = "Смычковый синтезаторный звук"},
new Instrument { Id = 93, Name = "Metallic Pad", TranslatedName = "Металлический синтезаторный звук"},
new Instrument { Id = 94, Name = "Halo Pad", TranslatedName = "Ореол"},
new Instrument { Id = 95, Name = "Sweep Pad", TranslatedName = "Качающийся звук"},
new Instrument { Id = 96, Name = "Rain", TranslatedName = "Дождь"},
new Instrument { Id = 97, Name = "Soundtrack", TranslatedName = "Звуковая дорожка"},
new Instrument { Id = 98, Name = "Crystal", TranslatedName = "Хрусталь"},
new Instrument { Id = 99, Name = "Atmosphere", TranslatedName = "Атмосфера"},
new Instrument { Id = 100, Name = "Brightness", TranslatedName = "Яркость"},
new Instrument { Id = 101, Name = "Goblins", TranslatedName = "Гоблины"},
new Instrument { Id = 102, Name = "Echo Sweep", TranslatedName = "Качающееся эхо"},
new Instrument { Id = 103, Name = "Sci Fi", TranslatedName = "SciFi"},
new Instrument { Id = 104, Name = "Sitar", TranslatedName = "Ситар"},
new Instrument { Id = 105, Name = "Banjo", TranslatedName = "Банджо"},
new Instrument { Id = 106, Name = "Shamisen", TranslatedName = "Шамисен"},
new Instrument { Id = 107, Name = "Koto", TranslatedName = "Кото"},
new Instrument { Id = 108, Name = "Kalimba", TranslatedName = "Калимба"},
new Instrument { Id = 109, Name = "Bagpipe", TranslatedName = "Волынка"},
new Instrument { Id = 110, Name = "Fiddle", TranslatedName = "Уличная скрипка"},
new Instrument { Id = 111, Name = "Shanai", TranslatedName = "Санаи"},
new Instrument { Id = 112, Name = "Tinkle Bell", TranslatedName = "Звенящий колокольчик"},
new Instrument { Id = 113, Name = "Agogo", TranslatedName = "Агого"},
new Instrument { Id = 114, Name = "Steel Drums", TranslatedName = "Стальные барабаны"},
new Instrument { Id = 115, Name = "Woodblock", TranslatedName = "Коробочка (гольцтон)"},
new Instrument { Id = 116, Name = "Taiko Drum", TranslatedName = "Таико"},
new Instrument { Id = 117, Name = "Melodic Tom", TranslatedName = "Мелодический томтом"},
new Instrument { Id = 118, Name = "Synth Drum", TranslatedName = "Синтезированный барабан"},
new Instrument { Id = 119, Name = "Reverse Cymbal", TranslatedName = "Реверсивная тарелка (запись в обратную сторону)"},
new Instrument { Id = 120, Name = "Guitar Fret Noise", TranslatedName = "Шум гитарных ладов"},
new Instrument { Id = 121, Name = "Breath Noise", TranslatedName = "Дыхание"},
new Instrument { Id = 122, Name = "Seashore", TranslatedName = "Морской берег"},
new Instrument { Id = 123, Name = "Bird Tweet", TranslatedName = "Чириканье"},
new Instrument { Id = 124, Name = "Telephone Ring", TranslatedName = "Телефонный звонок"},
new Instrument { Id = 125, Name = "Helicopter", TranslatedName = "Вертолет"},
new Instrument { Id = 126, Name = "Applause", TranslatedName = "Аплодисменты"},
new Instrument { Id = 127, Name = "Gunshot", TranslatedName = "Выстрел"}
            };
        }
    }
}
